// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Book struct {
	ID       int32  `json:"id"`
	Title    string `json:"title"`
	Author   string `json:"author"`
	Category string `json:"category"`
}

type Chapter struct {
	ID     int32         `json:"id"`
	BookID sql.NullInt32 `json:"book_id"`
	Title  string        `json:"title"`
	Number sql.NullInt32 `json:"number"`
}

type Event struct {
	ID          int32           `json:"id"`
	GroupID     sql.NullInt32   `json:"group_id"`
	BookID      sql.NullInt32   `json:"book_id"`
	ChapterID   sql.NullInt32   `json:"chapter_id"`
	VideoLink   string          `json:"video_link"`
	StartTime   time.Time       `json:"start_time"`
	Duration    sql.NullFloat64 `json:"duration"`
	Description sql.NullString  `json:"description"`
	Canceled    sql.NullBool    `json:"canceled"`
	CreatedAt   sql.NullTime    `json:"created_at"`
}

type EventAttendee struct {
	ID      int32         `json:"id"`
	EventID sql.NullInt32 `json:"event_id"`
	UserID  sql.NullInt32 `json:"user_id"`
}

type EventSection struct {
	ID        int32         `json:"id"`
	EventID   sql.NullInt32 `json:"event_id"`
	SectionID sql.NullInt32 `json:"section_id"`
	Presenter sql.NullInt32 `json:"presenter"`
	Complete  sql.NullBool  `json:"complete"`
}

type Group struct {
	ID          int32          `json:"id"`
	Organizer   int32          `json:"organizer"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type GroupBook struct {
	ID           int32         `json:"id"`
	GroupID      sql.NullInt32 `json:"group_id"`
	BookID       sql.NullInt32 `json:"book_id"`
	Completion   float64       `json:"completion"`
	LastModified sql.NullTime  `json:"last_modified"`
}

type Section struct {
	ID        int32          `json:"id"`
	ChapterID sql.NullInt32  `json:"chapter_id"`
	Title     sql.NullString `json:"title"`
	Number    sql.NullInt32  `json:"number"`
}

type User struct {
	ID        int32        `json:"id"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	CreatedAt sql.NullTime `json:"created_at"`
}
