// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	BookExistsInGroup(ctx context.Context, bookID sql.NullInt32) (int64, error)
	CreateBook(ctx context.Context, arg CreateBookParams) (Book, error)
	CreateChapter(ctx context.Context, arg CreateChapterParams) (Chapter, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateEventAttendee(ctx context.Context, arg CreateEventAttendeeParams) (EventAttendee, error)
	CreateEventSection(ctx context.Context, arg CreateEventSectionParams) (EventSection, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateGroupBook(ctx context.Context, arg CreateGroupBookParams) (GroupBook, error)
	CreateSection(ctx context.Context, arg CreateSectionParams) (Section, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBook(ctx context.Context, id int32) error
	DeleteChapter(ctx context.Context, id int32) error
	DeleteEvent(ctx context.Context, id int32) error
	DeleteEventAttendee(ctx context.Context, id int32) error
	DeleteEventSection(ctx context.Context, id int32) error
	DeleteGroup(ctx context.Context, id int32) error
	DeleteGroupBook(ctx context.Context, id int32) error
	DeleteSection(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetBook(ctx context.Context, id int32) (Book, error)
	GetBooks(ctx context.Context) ([]Book, error)
	GetBooksByCategory(ctx context.Context, category string) ([]Book, error)
	GetChapter(ctx context.Context, id int32) (Chapter, error)
	GetChapters(ctx context.Context) ([]Chapter, error)
	GetChaptersByBook(ctx context.Context, bookID sql.NullInt32) ([]Chapter, error)
	GetEvent(ctx context.Context, id int32) (Event, error)
	GetEventAttendee(ctx context.Context, id int32) (EventAttendee, error)
	GetEventAttendeesByEvent(ctx context.Context, eventID sql.NullInt32) ([]EventAttendee, error)
	GetEventAttendeesByUser(ctx context.Context, userID sql.NullInt32) ([]EventAttendee, error)
	GetEventSection(ctx context.Context, id int32) (EventSection, error)
	GetEventSectionsByEvent(ctx context.Context, eventID sql.NullInt32) ([]EventSection, error)
	GetEvents(ctx context.Context) ([]Event, error)
	GetGroup(ctx context.Context, id int32) (Group, error)
	GetGroupBook(ctx context.Context, id int32) (GroupBook, error)
	GetGroupBooksByBook(ctx context.Context, bookID sql.NullInt32) ([]GroupBook, error)
	GetGroupBooksByGroup(ctx context.Context, groupID sql.NullInt32) ([]GroupBook, error)
	GetGroups(ctx context.Context) ([]Group, error)
	GetSection(ctx context.Context, id int32) (Section, error)
	GetSectionsByChapter(ctx context.Context, chapterID sql.NullInt32) ([]Section, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error)
	UpdateChapter(ctx context.Context, arg UpdateChapterParams) (Chapter, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdateEventAttendee(ctx context.Context, arg UpdateEventAttendeeParams) (EventAttendee, error)
	UpdateEventSection(ctx context.Context, arg UpdateEventSectionParams) (EventSection, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error)
	UpdateGroupBook(ctx context.Context, arg UpdateGroupBookParams) (GroupBook, error)
	UpdateSection(ctx context.Context, arg UpdateSectionParams) (Section, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
